### ISSUE TITLE
Add Fetch Dashboard

### ISSUE THREAD

**Issue by marvinruder** [marvinruder/rating-tracker#377]
**Describe the solution you’d like**
A dashboard allowing for fetching all stocks from a provider and showing the progress of these fetches using a progress bar.

**Describe alternatives you’ve considered**
OpenAPI dashboard or `curl`. No progress shown and bad usability.

**Comment by marvinruder** [comment]
Duplicate of #84.

**Comment by Gipsy9** [comment]
I dont now how its work im so bad time
